name: eneural_net
description: AI Library to create efficient Artificial Neural Networks. Computation uses SIMD (Single Instruction Multiple Data) to improve performance.
version: 1.1.1
homepage: https://eneural.net/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  swiss_knife: ^3.0.6
  intl: ^0.17.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.1
  dependency_validator: ^3.1.0
